$content = @"
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN

android {
  compileOptions {
      sourceCompatibility JavaVersion.VERSION_11
      targetCompatibility JavaVersion.VERSION_11
  }
}

apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
dependencies {
    implementation project(':capacitor-cordova-android-plugins')
}

if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}
"@

$content | Out-File -FilePath "android\app\capacitor.build.gradle" -Encoding utf8
Write-Host "Java version fixed in capacitor.build.gradle!" 